version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - webflux_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
        - 5432:5432

volumes:
    webflux_data: